[build]
  command = "npm run build"
  publish = ".next"

# Remove the Next.js plugin since we're not using SSR features
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

# Add proper redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

